PREFIX obo: <http://purl.obolibrary.org/obo/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX sbdbel: <https://h2020-sbd4nano.github.io/sbdbel/>
PREFIX sio: <http://semanticscience.org/resource/SIO_>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX cito: <http://purl.org/net/cito/>
PREFIX aopo: <http://aopkb.org/aop_ontology#>
PREFIX enm: <http://purl.enanomapper.org/onto/>
PREFIX bao: <http://www.bioassayontology.org/bao#>
PREFIX npo: <http://purl.bioontology.org/ontology/npo#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?erm ?materialLabel ?cause ?relationship ?outcome ?quote ?doi
WHERE {
    ?causalAssertion a sio:001183 .                           # A causal assertion
    ?causalAssertion sio:000206 ?evidence .                   # Which is supported by an evidence
    ?evidence sbdbel:quote ?quote .                           # Get the quote
    ?evidence cito:containsAssertionFrom/owl:sameAs ?doi .    # Get DOI from evidence
    ?causalAssertion sbdbel:hasCause ?causeIri .              # Get cause
    ?causeIri rdfs:label ?cause .                             # Get cause label
    ?causalAssertion sbdbel:hasRelationship ?relIri .         # Get relationship
    ?relIri rdfs:label ?relationship .                        # Get relationship label
    ?causalAssertion sbdbel:hasOutcome ?outcomeIri .          # Get outcome
    ?outcomeIri rdfs:label ?outcome .                         # Get outcome label
    ?causalAssertion sio:000332 ?material .                   # Get material
    ?material dcterms:identifier ?erm .                       # Get material identifier
    ?material a ?materialType .                               # Get material type
    ?materialType rdfs:label ?materialLabel .                 # Get material type label

    {
      ?materialType rdfs:subClassOf* enm:ENM_0000117 .         # Ensure material type is subclass of GO
    
    } UNION {
      ?materialType rdfs:about enm:ENM_0000117 .               # Also select causeIri if it is GO
    }                     

    OPTIONAL {
        ?outcomeIri rdfs:subClassOf* ?outcomeSuperclassIri .  # Get outcome superclass
    }

    FILTER (
        (?relationship = "negatively_correlates" && ?outcomeSuperclassIri IN ( 
            aopo:AdverseOutcome,
            enm:ENM_0000037,  # Oxidative stress
            bao:BAO_0000201,  # Percent inhibition
            enm:ENM_0000018,  # Toxicological endpoint
            obo:OAE_0000001,  # Adverse event
            obo:GO_1902806,   # Negative regulation of cell cycle
            obo:GO_0051494,   # Negative regulation of cytoskeleton regulation
            obo:GO_1901800    # Positive regulation of proteasomal protein catabolic process
        ))
        ||
        (?relationship = "positively_correlates" && ?outcomeSuperclassIri IN ( 
            bao:BAO_0002162,  # Concentration response endpoints (IC, EC, AC, LC)
            enm:NM_0000068,   # Viability
            obo:GO_1903786    # Negative regulation of GSH
        ))
    )
}
